spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
    jpa:
        show-sql: true
    jackson:
      default-property-inclusion: non_null
server:
    context-path: /sell
    port: 8088
wechat:
    mpAppId: wx6f4a93e30d824a1d
    mpAppSecret: 12c1f30c12b38a8766570cfc292ecf70
    mchId: 140914202
    mchKey: c976503d34ca432c601361f969fd8d85
    keyPath: /var/weixin_cert/h5.p12
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  #path: var/log/tomcat/
#  file: var/log/tomcat/sell.log
#  level:
#    com.wkze.sell.LoggerTest: debug
